README.md, _CONTRIBUTING.md, _PRESS-RELEASE.md, _README.md, _STYLE_GUIDE.md
This push is just for the initial files.
=> Initial files

.bowerrc, .gitignore, npm-debug.log, package.json, server/public/index.html, server/server.js
Sets a very bare project scaffold:
* `npm install` for node modules (express was included)
* `bower install` should send bower files to server/public/bower
* `npm test` sets up the project on port 3000
Nothing too fancy.
=> Scaffolding

.gitignore, Gulpfile.js, client/index.html, client/js/actions/action.js, client/js/constants/constant.js, client/js/stores/store.js, package.json
+ Created file struture for working with React & Flux
+ Updated Gulp file to use browserfy, reactify, & vinyl-source-stream
+ Included browserfy task to bundle required modules
+ Included copy task for copying into our dist folder
+ Added a watcher for our client directory
+ Added script tag for main.js
=> File structure for React & Flux. Updated Gulp.

client/styles/normalize.css, client/styles/skeleton.css
skeleton.css
normalize.css
db.js
=> added skeleton, db.js

server/config/config.js, server/db/db.js, server/models/teammodel.js, server/models/usermodel.js
Set up database configuration:
* db.js creates database connection
* db used instead of competing 'sequelize/Sequelize' namespace in schemas
* db configuration located in config.js
* secret removed from config.js, will instead have a gitignored secret stash in the future for private information
=> database config

.gitignore, package.json, server/routes/handler.js, server/routes/user.js
Created a route that returns an object representing a player's data from Riot's server. The route can be accessed by going to `localhost:3000/lol/(region abbr)/(username)`, such as `localhost:3000/lol/na/nexas`. Should more information be required it can be added to this route.
=> API routing

package.json, server/controllers/user.controller.js, server/models/teammodel.js, server/models/usermodel.js, server/server.js, server/views/index.ejs
`npm install` will be required due to new module inclusion
* database schemas fixed - namely an issue of trying to use default values as data types
* unnecessary dependencies removed
* otherwise, code cleanup from previous commits
=> Debug pass

.bowerrc, _CONTRIBUTING.md, _PRESS-RELEASE.md, _README.md, _STYLE_GUIDE.md, server/config/config.js, server/routes/handler.js
This is primarily a readme update, although it does clean a few things up on the side.
=> Readme update, minor touch-ups

client/index.html, client/js/components/about/app-about.js, client/js/components/app-template.js, client/js/components/app.js, client/js/components/header/app-header.js, client/js/components/landing/app-landing.js, client/js/components/registration/registration.js, client/js/components/team/team-profile.js, client/js/constants/constant.js, client/js/main.js
Added basic routing using react-router-component
Added header, about, & landing components
In Progress - Refactoring react-router-component to use react-router
=> basic routing, header, about, & landing component

package.json, server/routes/userroutes.js, server/server.js
=> passport attempt

client/js/components/app-template.js, client/js/components/app.js, client/js/components/header/app-header.js, client/js/main.js, client/js/mixins/AuthMixin.js, package.json
Updated routing to use react-route
Added in AuthMixin file
=> React router

server/routes/user.routes.js
reformatted into promise style
changed find One
=> login now works

server/controllers/user.controller.js, server/routes/user.routes.js
changepassword works, for now I am updating the field activationKey (since there is no password field, discuss with sean)
Also if you do a postman request will timeout, but inspect the db and the changes were made.
=> changepassword works

server/config/db.js, server/config/magic.js, server/controllers/user.controller.js, server/models/team.model.js, server/models/user.model.js, server/routes/user.routes.js, server/server.js
* User/Team schemas adjusted to use more fluid JSON fields instead of trying to predict our schema during week 1
* Passport.use logic moved out of routes and into magic.js passport handler to allow routes to focus on routing logic
=> Schema adjustment, logic movement

package.json, server/routes/handler.js
* Unranked players should now show up as "unranked" (previously 404'd)
* Heroku postinstall script added for deployment
=> player json update and heroku postinstall

Gulpfile.js, server/controllers/team.controller.js, server/routes/team.routes.js
fixed some whitespace on gulpfile
added getprofile and update profile routes / helper functions
=> added team oriented routes and helper functions

client/index.html
=> Updated landing page

server/controllers/team.controller.js, server/models/team.model.js, server/routes/team.routes.js, server/server.js
=> team profile routes fixed

client/index.html, client/js/components/user-profile/user-questions.js
copy taken from press release. edited just to fix line-breaks and make everything square.
=> questionnaire bug fix; added text to landing page

server/controllers/user.controller.js, server/routes/user.routes.js, server/server.js
This change applies logic to the `/` route, which means when you do register/login you will not be sent to some weird url like `/login#/` but rather maintain the `/#/` route that looks nice and clean.
=> contextual main route

.gitignore, client/js/components/header/app-header.js
added recruitment to the icons, as well as dropdown and sign out.
=> Navbar Changes

client/index.html, client/js/components/header/app-header.js, client/js/routes.js, client/main.html, server/server.js
And it's all in React - I also implemented it in main.html just in case, but it's commented out until a decision is reached.
=> working navbar component, complete with dropdown =D

client/js/components/header/app-header.js, client/js/components/user-profile/settings.js, client/js/routes.js, client/main.html, server/controllers/user.controller.js, server/routes/user.routes.js
The problem/benefit (?) with being restless ~_~
* I finally got my hands dirty with React (yay)
* Navbar is now team-aware and displayName-aware
* Navbar now allows for logging out through settings-cog
* Settings route and view were made
TODO
* When displayName is changed there needs to be an event emission so the navbar knows to change
* This will likely need to be extended to profile pics and team insertion/removal
* Need to find out where data is being bound so I know how to better render the template
=> features for navbar, settings route and page

client/js/components/header/app-header.js, client/js/components/user-profile/bio-form.js, client/js/components/user-profile/bio.js, client/js/components/user-profile/profile.js, client/js/components/user-profile/settings.js, package.json, server/controllers/user.controller.js
Fixes setting hanging after submit.
removed get initial state since settings is a child component of profile, instead passed display name as a prop and state is passed with State.Router mixin
=> set setting transition back to profile

server/controllers/team.controller.js, server/routes/team.routes.js
get all teams by doing a get request to /team/all
=> added get all teams route

client/js/components/header/app-header.js, client/js/components/recruitment/findTeams.js, client/js/components/user-profile/profile.js, client/js/routes.js, server/models/user.model.js, test/ratingSpec.js
- recruitment works for single users for now while we still configure teams
- TODO: fix math.
- TODO: create default fields in user bio
=> recruitment page populates
